version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: novya_backend
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ai_backend:
        condition: service_started

  ai_backend:
    build:
      context: ./backend/ai_backend
      dockerfile: Dockerfile.ai
    container_name: ai_backend
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./novya-frontend-main
      dockerfile: Dockerfile.frontend
    container_name: novya_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_novya
    environment:
      POSTGRES_DB: novya
      POSTGRES_USER: novya
      POSTGRES_PASSWORD: novya123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novya"]
      interval: 5s
      retries: 5
      timeout: 3s

  redis:
    image: redis:7
    container_name: novya_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

